[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = ".next"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
